/**
 * ChangeTrackerAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TakealotItemCreated { 
    plid?: string | null;
    name?: string | null;
    raw_value?: any | null;
}

