/**
 * ChangeTrackerAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TakealotSearchRequest { 
    pageNumber?: number;
    pageSize?: number;
    sortBy?: string | null;
    descending?: boolean;
    name?: string | null;
    last_updated_start?: Date | null;
    last_updated_end?: Date | null;
    product_id?: string | null;
    in_stock?: boolean | null;
}

