/**
 * ChangeTrackerAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TakealotItemRequested } from './takealot-item-requested';


export interface TakealotItemRequestedVTEvent { 
    sequence?: number;
    event_id?: string;
    correlation_id?: string;
    causation_id?: string;
    created?: Date;
    data?: TakealotItemRequested;
    type?: string | null;
    stream?: string | null;
    client_id?: string | null;
    actor_id?: string | null;
    description?: string | null;
}

